// template-managed (bootstrap): do not edit; endpoints are injected by the
// generated client (src/store/generatedApi.ts, regenerated by `just
// api-client`). Delete this line to take ownership.
import {
  type BaseQueryApi,
  type BaseQueryFn,
  createApi,
  type FetchArgs,
  type FetchBaseQueryError,
  fetchBaseQuery,
} from "@reduxjs/toolkit/query/react";
import { clearTokens, saveTokens } from "../auth/tokens";
import { type AuthState, clearCredentials, setCredentials } from "./authSlice";

// Always relative: Vite proxies /api in dev, the gateway routes it in
// production. No CORS in any environment.
const rawBaseQuery = fetchBaseQuery({
  baseUrl: "/",
  // The gateway answers or fails within 15 s; this only guards against a
  // connection that never completes.
  timeout: 30_000,
  prepareHeaders: (headers, { getState }) => {
    const { auth } = getState() as { auth: AuthState };
    if (auth.access !== null) {
      headers.set("Authorization", `Bearer ${auth.access}`);
    }
    return headers;
  },
});

type ExtraOptions = Parameters<typeof rawBaseQuery>[2];

function selectAuth(api: BaseQueryApi): AuthState {
  return (api.getState() as { auth: AuthState }).auth;
}

// Same steps as the logout thunk (src/auth/logout.ts), which cannot be
// imported here without a cycle: it resets this api's state.
function expireSession(api: BaseQueryApi): void {
  clearTokens();
  api.dispatch(clearCredentials());
  api.dispatch(baseApi.util.resetApiState());
}

// One refresh at a time: concurrent 401s await this shared promise, so a
// rotated refresh token is never presented twice (the second presentation
// would fail and log the user out). Resolves to whether the session lives on.
let refreshInFlight: Promise<boolean> | null = null;

function refreshSession(
  api: BaseQueryApi,
  extraOptions: ExtraOptions,
): Promise<boolean> {
  refreshInFlight ??= (async () => {
    const { refresh } = selectAuth(api);
    if (refresh === null) {
      return false;
    }
    const refreshed = await rawBaseQuery(
      {
        url: "/api/v1/auth/token/refresh/",
        method: "POST",
        body: { refresh },
      },
      api,
      extraOptions,
    );
    const data = refreshed.data as
      | { access?: string; refresh?: string }
      | undefined;
    if (data?.access === undefined) {
      expireSession(api);
      return false;
    }
    const tokens = { access: data.access, refresh: data.refresh ?? refresh };
    api.dispatch(setCredentials(tokens));
    saveTokens(tokens);
    return true;
  })().finally(() => {
    refreshInFlight = null;
  });
  return refreshInFlight;
}

// On 401: refresh once (shared across concurrent requests), retry the
// original request; if the refresh fails the session is over.
const baseQueryWithReauth: BaseQueryFn<
  string | FetchArgs,
  unknown,
  FetchBaseQueryError
> = async (args, api, extraOptions) => {
  const accessUsed = selectAuth(api).access;
  const result = await rawBaseQuery(args, api, extraOptions);
  if (result.error?.status !== 401 || selectAuth(api).refresh === null) {
    return result;
  }
  // A refresh that completed while this request was in flight already
  // replaced the token: retry without refreshing again.
  const refreshed =
    selectAuth(api).access !== accessUsed ||
    (await refreshSession(api, extraOptions));
  return refreshed ? rawBaseQuery(args, api, extraOptions) : result;
};

export const baseApi = createApi({
  reducerPath: "api",
  baseQuery: baseQueryWithReauth,
  endpoints: () => ({}),
  // Active queries refetch when the browser comes back online (main.tsx
  // wires the events with setupListeners). refetchOnFocus stays off: every
  // tab switch would refetch every mounted query; turn it on per hook where
  // staleness is visible to the user.
  refetchOnReconnect: true,
});
